apiVersion: apps/v1
kind: Deployment  
metadata:
  name: nextjs-app-deploy
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      name: nextjs-pod
      namespace: development
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app-cont
          image: ahmedatya11/nextjs-app
          ports:
            - containerPort: 3000